package ua.com.serzh.borisov;

import lombok.extern.slf4j.Slf4j;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import static java.time.LocalDate.now;
import static java.time.LocalTime.of;
import static java.time.ZoneId.systemDefault;
import static java.util.Date.from;

/**
 * Created by Serzh on 2/5/17.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = ApplicationConfiguration.class)
//@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
@Slf4j
public class MongoMainTest {

    private static final Logger log = LoggerFactory.getLogger(MongoMainTest.class);// this line will be generated by lombok in compile phase because of @Slf4j

    @Autowired
    private SpeakerRepository speakerRepository;

    @Before
//    @Transactional
//    @Rollback(false)  relevant only for relational database
    public void setUp() {

        Speaker jeka = new Speaker("Evgeny Borisov");
        jeka.addTalk(new Talk("Spring The Ripper", time("12:30")));
        jeka.addTalk(new Talk("Spring Data", time("17:30")));


        Speaker nikolay = new Speaker("Nikolay Alimenkov");
        nikolay.addTalk(new Talk("CD JEE7", time("18:00")));

        Speaker baruch = new Speaker("Baruch Sadogursky");
        baruch.addTalk(new Talk("AST Groovy", time("12:00")));
        baruch.addTalk(new Talk("Making Spring Groovy", time("09:00")));

        speakerRepository.save(Arrays.asList(baruch, jeka, nikolay));

        String check = "Check";
    }

    @Test
    public void testCount() {
        log.info("Speaker count: " + speakerRepository.count());

    }

    @Test
    public void testFindAll() {
        log.info("************  Speaker names **********************");
        List<Speaker> allSpeakers = speakerRepository.findAll();
        for (Speaker speaker : allSpeakers) {
            log.info(speaker.getName());
        }
        log.info("************  Speaker names **********************");
    }

   /* @Test
    public void testFindByName() {
        log.info("********* ALL Talks of Evgeny ***********");
        Speaker speaker = speakerRepository.findByNameStartingWith("Evgeny Borisov").get(0);
        speaker.getTalks().forEach(System.out::println);
        log.info("********* ALL Talks of Evgeny ***********");
    }

    @Test
    public void testFindByNameLike() {
        log.info("********* ALL SPEAKERS WITH ov ***********");
        List<Speaker> speakers = speakerRepository.findPleeeeaseByNameEndingWith("ov");
        speakers.forEach(System.out::println);
        log.info("********* ALL SPEAKERS WITH ov ***********");

    }*/

   /* @Test
    public void testFindSpeakersWithTalksBetween() {
        log.info("********* Talks between 08:00 and 13:00 ***********");
        List<Speaker> speakers = speakerRepository.findByTalksWhenBetween(time("08:00"), time("13:00"));
        speakers.forEach(System.out::println);
        log.info("********* ***************************** ***********");

    }*/

   /* @Test
    public void testFindTalksBetween() {
        log.info("********* Talks between 08:00 and 13:00 ***********");
        List<Talk> matchingTalks = speakerRepository.findTalksBetween(time("08:00"), time("13:00"));
        matchingTalks.forEach(t -> log.info(t.toString()));
        log.info("********* ***************************** ***********");

    }

    @Test
    public void testGetSpeakersWithTalksAboutSpring() {
        log.info("********* Speakers talking about Spring ***********");
        Set<Speaker> matchingSpeakers = speakerRepository.findByTalksTitleContaining("Spring");
        matchingSpeakers.forEach(t -> log.info(t.toString()));
        log.info("********* ***************************** ***********");
    }
*/
    @After
    public void clean() {
        speakerRepository.deleteAll();
    }

    private Date time(String time) {
        String[] split = time.split(":");
        int hours = Integer.parseInt(split[0]);
        int minutes = Integer.parseInt(split[1]);
        return from(of(hours, minutes).atDate(now()).atZone(systemDefault()).toInstant());
    }
}
